name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
        dummy:
            required: false
            type: boolean

permissions:
  contents: read
  checks: write

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --user root --workdir /
    steps:
      - name: Update and install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -Sy --noconfirm python python-pip python-pytest qt6-declarative coreutils nodejs npm python-build wget python-coverage

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get bundled qmldom
        run: |
          wget https://github.com/SanderVocke/qoverage/releases/download/qmldom-6.5.3-v1.0.0/qmldom-6.5.3-linux-x64
          mkdir -p qoverage/bundled_qmldom
          mv qmldom-6.5.3-linux-x64 qoverage/bundled_qmldom/qmldom
          chmod a+x qoverage/bundled_qmldom/qmldom

      - name: Build
        run: |
            python -m build -w .
            echo "wheel_path=$(ls dist/*.whl)" | tee -a $GITHUB_ENV
            cd dist && echo "wheel_filename=$(ls *.whl)" | tee -a $GITHUB_ENV

      - name: Upload wheel
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.wheel_filename }}
          path: ${{ env.wheel_path }}
      
      - name: Prepare coverage settings
        run: rm -f .coverage* && echo "${{ env.FILE_CONTENTS }}" > "${{ env.FILE_NAME }}"
        env:
          FILE_NAME: .coveragerc
          FILE_CONTENTS: |
            [run]
            branch = True
            parallel = True
            source = .
    
      - name: Run Tests With Coverage
        shell: bash
        run: >
          mkdir -p /tmp/generated &&
          printf "import coverage\ncoverage.process_startup()\n" > sitecustomize.py &&
          export PYTHONPATH=$PYTHONPATH:$(pwd) &&
          QT_ASSUME_STDERR_HAS_CONSOLE=1
          OUTPUT_DIR=/tmp/generated
          QOVERAGE_LOGLEVEL=debug
          QOVERAGE="python -m qoverage"
          DUMP_RUN_LOG=1
          QT_QPA_PLATFORM=vnc
          QML=/usr/lib/qt6/bin/qml
          QMLTESTRUNNER=/usr/lib/qt6/bin/qmltestrunner
          QML_IMPORT_PATH=$(pwd)/qoverage/qml_import
          COVERAGE_PROCESS_START=.coveragerc
          python -m coverage run -m pytest . --junit-xml=pytest.xml --verbose
          -k 'test_example[for]'
      
      - name: Generate Pytest coverage report
        run: |
          rm -f coverage.xml
          python -m coverage combine .coverage.*
          python -m coverage xml -i -o coverage.xml
      
      # - name: Install wheel and run qoverage from command-line
      #   run: |
      #     python -m pip install --break-system-packages dist/*.whl
      #     qoverage -h
      #     cd /tmp && qoverage -h
      #     cd /tmp && python -m qoverage -h

      - name: Upload generated code
        if: ${{ (success() || failure()) && !env.ACT }}
        uses: actions/upload-artifact@v3
        with:
          name: generated_code
          path: /tmp/generated

      - name: Publish Python Test Report
        if: ${{ (success() || failure()) && !env.ACT }}
        uses: mikepenz/action-junit-report@v3
        with:
            report_paths: pytest.xml
            detailed_summary: true
            include_passed: true
            check_name: 'pytest'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
