name: Build qmldom emscripten

on:
  workflow_dispatch:
    inputs:
      force-rebuild:
        description: 'Force rebuild even if this version is already present in the cache.'
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  checks: write

jobs:
  qmldom_wasm:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --user root --workdir /
    steps:
      - name: Update and install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -Sy --noconfirm coreutils nodejs npm wget git cmake mesa ninja llvm clang rsync cargo rust lld unzip

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Short git sha
        run: |
          echo "git_sha=$(git rev-parse --short $GITHUB_SHA)" | tee -a $GITHUB_ENV
      
      - name: Install WASIX sysroot
        run: |
          wget https://github.com/SanderVocke/wasix-sysroot/releases/download/v1.0.0/wasix-sysroot.zip
          rm -rf /opt/wasix-sysroot
          unzip wasix-sysroot.zip -d /opt/wasix-sysroot

      - name: Checkout Qt sources
        run: |
          if [ ! -d "qt6" ]; then git clone git://code.qt.io/qt/qt5.git qt6; fi
          cd qt6
          git fetch origin dev && git checkout origin/dev
          ./init-repository -f --module-subset=qtbase,qtdeclarative

      - name: Checkout Qt sources (host)
        run: |
          if [ ! -d "qt6-host" ]; then echo $(pwd) && git clone ./qt6 qt6-host; fi
          cd qt6-host
          git fetch origin dev && git checkout origin/dev
          git remote remove origin
          git remote add origin git://code.qt.io/qt/qt5.git
          ./init-repository -f --module-subset=qtbase

      - name: Configure Qt6 (host)
        run: |
          mkdir -p qt6-build-host
          cd qt6-build-host && ../qt6-host/configure -prefix /opt/qt6 -shared -no-opengl
      
      - name: Build Qt6 (host)
        run: |
          cd qt6-build-host && cmake --build . --parallel 4
      
      - name: Install Qt6 (host)
        run: |
          cd qt6-build-host && cmake --install .
        
      - name: Patch Qt6
        run: |
          cd qt6/qtbase && git am ../../.github/workflows/files/qt6.*.patch

      - name: Configure Qt6 (WASM)
        run: |
          mkdir -p qt6-build
          cd qt6-build
          ../qt6/configure -prefix /opt/qt6-wasm -static -no-opengl -platform wasm-emscripten -qt-host-path /opt/qt6 -make qmldom -- --fresh -DCMAKE_TOOLCHAIN_FILE=/opt/wasix-sysroot/clang-wasix.cmake_toolchain
      
      - name: Build qmldom
        run: |
          cd qt6-build
          cmake --build . --parallel 4 --target qmldom.js
     
      - name: Upload qmldom
        uses: actions/upload-artifact@v2
        with:
          name: qmldom-emscripten
          path: qt6-build/qtbase/bin/qmldom*

            