name: Build standalone qmldom tool

on:
  workflow_dispatch:
    inputs:
      force-rebuild:
        description: 'Force rebuild even if this version is already present in the cache.'
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  checks: write

jobs:
  qmldom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake ninja-build python3 gcc clang llvm-14 libclang-14-dev libgl1-mesa-dev libglu1-mesa-dev libicu-dev llvm-14-dev

      - name: Cache qmldom build
        id: cache-qmldom
        uses: actions/cache@v3
        with:
          path: qmldom
          key: qmldom-6.5.2

      - name: Print cache status for qmldom
        run: |
          echo "Cache hit: ${{ steps.cache-qmldom.outputs.cache-hit }}"
           
      - if: ${{ github.event.inputs.force-rebuild == 'true' || steps.cache-qmldom.outputs.cache-hit != 'true' }}
        name: Download Qt sources
        run: |
            wget https://download.qt.io/official_releases/qt/6.5/6.5.2/single/qt-everywhere-src-6.5.2.tar.xz
            tar -xf qt-everywhere-src-6.5.2.tar.xz
            mv qt-everywhere-src-6.5.2 qt
    
      - if: ${{ github.event.inputs.force-rebuild == 'true' || steps.cache-qmldom.outputs.cache-hit != 'true' }}
        name: Configure Qt
        run: |
            mkdir qt-build
            cd qt-build
            ../qt/configure -static -no-icu -qt-pcre -qt-zlib
            ls -la
            ls -la *
    
      - if: ${{ github.event.inputs.force-rebuild == 'true' || steps.cache-qmldom.outputs.cache-hit != 'true' }}
        name: Build Qt
        run: |
            cd qt-build
            cmake --build . --parallel 4 --target qmldom
            cp qtbase/bin/qmldom ../qmldom
      
      - name: Upload qmldom
        uses: actions/upload-artifact@v2
        with:
          name: qmldom
          path: qmldom

            