name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
        dummy:
            required: false
            type: boolean

permissions:
  contents: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --user root --workdir /
    steps:
      - name: Update and install dependencies
        run: |
            pacman -Syu --noconfirm
            pacman -Sy --noconfirm python python-build python-pip python-pytest qt6-declarative

      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Run Tests
        run: |
            QT_QPA_PLATFORM=vnc QMLDOM=/usr/lib/qt6/bin/qmldom QML=/usr/lib/qt6/bin/qml pytest test --junit-xml=pytest.xml

      - name: Publish Python Test Report
        if: ${{ !env.ACT }}
        uses: mikepenz/action-junit-report@v3
        with:
            report_paths: pytest.xml
            detailed_summary: true
            include_passed: true
            check_name: 'pytest'
